In [1]:
import pandas as pd

Zakomentowane wczytywanie plików niepotrzebnych do merga z innym zbiorem, bo zajmuje więcej czasu (ok. 7 minut) - można odkomentować

In [6]:
# names = pd.read_csv('../data/imdb/name.basics.tsv.gz', sep='\t')
# names.head()

In [7]:
# title_akas = pd.read_csv('../data/imdb/title.akas.tsv.gz', sep='\t')
# title_akas.head()

In [2]:
title_basics = pd.read_csv('../data/imdb/title.basics.tsv.gz', sep='\t')
title_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [9]:
# title_crew = pd.read_csv('../data/imdb/title.crew.tsv.gz', sep='\t')
# title_crew.head()

In [10]:
# title_episode = pd.read_csv('../data/imdb/title.episode.tsv.gz', sep='\t')
# title_episode.head()

In [11]:
# title_principals = pd.read_csv('../data/imdb/title.principals.tsv.gz', sep='\t')
# title_principals.head()

In [12]:
# title_ratings = pd.read_csv('../data/imdb/title.ratings.tsv.gz', sep='\t')
# title_ratings.head()

In [3]:
title_movies = title_basics[(title_basics['primaryTitle'].notna()) & (title_basics['titleType'] == 'movie')].copy()

In [4]:
title_movies['startYear'] = pd.to_numeric(title_movies['startYear'], errors='coerce')
title_movies = title_movies[(title_movies['startYear'] >= 1900) & (title_movies['startYear'] < 2026)]
title_movies.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
498,tt0000502,movie,Bohemios,Bohemios,0,1905.0,\N,100,\N
570,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906.0,\N,70,"Action,Adventure,Biography"
587,tt0000591,movie,The Prodigal Son,L'enfant prodigue,0,1907.0,\N,90,Drama
610,tt0000615,movie,Robbery Under Arms,Robbery Under Arms,0,1907.0,\N,\N,Drama
625,tt0000630,movie,Hamlet,Amleto,0,1908.0,\N,\N,Drama

In [5]:
title_movies[(title_movies['primaryTitle'] == "Avatar") & (title_movies['startYear'] == 2009)]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
479801,tt0499549,movie,Avatar,Avatar,0,2009.0,\N,162,"Action,Adventure,Fantasy"

In [6]:
box_office = pd.read_csv("../data/worldwide-box-office/boxoffice.csv")
merged = pd.merge(
    title_movies,
    box_office,
    left_on=['originalTitle', 'startYear'],
    right_on=['title', 'year']
)

In [7]:
print(len(title_movies))
print(len(merged[merged['title'].notna()]))

624222
16820

Na 624 222 filmy pomiędzy rokiem 1900 a 2025 ze źródeł IMDB, 16 822 udało się dopasować do danych z Worldwide Box Office.

In [8]:
merged.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,title,domestic_million_usd,overseas_million_usd,world_million_usd,year
0,tt0003471,movie,Traffic in Souls,Traffic in Souls,0,1913.0,\N,88,"Crime,Drama",Traffic in Souls,1.0,NaN,1.0,1913.0
1,tt0003743,movie,The Call of the North,The Call of the North,0,1914.0,\N,\N,"Adventure,Drama",The Call of the North,0.1,NaN,0.1,1914.0
2,tt0004294,movie,The Man from Home,The Man from Home,0,1914.0,\N,\N,Drama,The Man from Home,0.1,NaN,0.1,1914.0
3,tt0004336,movie,The Million Dollar Mystery,The Million Dollar Mystery,0,1914.0,\N,\N,"Adventure,Mystery,Romance",The Million Dollar Mystery,3.3,NaN,3.3,1914.0
4,tt0004545,movie,Rose of the Rancho,Rose of the Rancho,0,1914.0,\N,50,"Action,Adventure,Drama",Rose of the Rancho,0.1,NaN,0.1,1914.0