In [139]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv(('../data/merged/clean_data.csv')) # z notatnika cleaning.ipynb

In [141]:
data.columns

Index(['tmdbId', 'title', 'budget', 'revenue', 'release_date', 'runtime',
       'original_language', 'popularity', 'vote_average', 'vote_count',
       'origin_countries', 'spoken_languages', 'year', 'keywords', 'genres',
       'director_id', 'director_name', 'director_popularity',
       'director_gender', 'writer_id', 'writer_name', 'writer_popularity',
       'writer_gender', 'actor4_id', 'actor4_name', 'actor4_popularity',
       'actor4_gender', 'actor2_id', 'actor2_name', 'actor2_popularity',
       'actor2_gender', 'actor1_id', 'actor1_name', 'actor1_popularity',
       'actor1_gender', 'actor5_id', 'actor5_name', 'actor5_popularity',
       'actor5_gender', 'actor3_id', 'actor3_name', 'actor3_popularity',
       'actor3_gender', 'budget_adjusted', 'revenue_adjusted', 'quarter',
       'epoka', 'main_genre', 'one_or_more_origin', 'origin_in_US',
       'origin_in_top_5'],
      dtype='object')

## Usuwanie braków i złych wartości zmiennych

In [142]:
data = data[['tmdbId', 'title','release_date', 'runtime',
       'original_language', 'vote_average', 'vote_count',
       'origin_countries', 'spoken_languages', 'year', 'keywords', 'genres',
       'director_id', 'director_name', 'director_gender',
       'writer_id', 'writer_name', 'writer_gender',
       'actor4_id', 'actor4_name', 'actor4_gender',
       'actor2_id', 'actor2_name', 'actor2_gender',
       'actor1_id', 'actor1_name', 'actor1_gender',
       'actor5_id', 'actor5_name', 'actor5_gender',
       'actor3_id', 'actor3_name', 'actor3_gender',
       'budget_adjusted', 'revenue_adjusted', 'quarter', 'main_genre']]

In [143]:
data = data[data["budget_adjusted"] > 0]

In [144]:
data.shape

(11583, 37)

In [145]:
data = data[data["year"] > 1979]

In [146]:
data.shape

(10591, 37)

In [147]:
data[data["runtime"] > 60]

,tmdbId,title,release_date,runtime,original_language,vote_average,vote_count,origin_countries,spoken_languages,year,...,actor5_id,actor5_name,actor5_gender,actor3_id,actor3_name,actor3_gender,budget_adjusted,revenue_adjusted,quarter,main_genre
0,5.0,Four Rooms,1995-12-09,98,en,5.892,2810,['UnitedStatesofAmerica'],English,1995,...,3125.0,Madonna,1.0,3130.0,Jennifer Beals,1.0,8.449948e+06,8.993604e+06,4,comedy
1,6.0,Judgment Night,1993-10-15,109,en,6.469,368,['UnitedStatesofAmerica'],English,1993,...,9777.0,Cuba Gooding Jr.,2.0,12799.0,Jeremy Piven,2.0,4.678756e+07,2.704085e+07,4,action
3,12.0,Finding Nemo,2003-05-30,100,en,7.817,20364,['UnitedStatesofAmerica'],English,2003,...,12.0,Alexander Gould,2.0,118.0,Geoffrey Rush,2.0,1.644709e+08,1.645296e+09,2,animation
4,13.0,Forrest Gump,1994-06-23,142,en,8.500,29387,['UnitedStatesofAmerica'],English,1994,...,32.0,Robin Wright,1.0,35.0,Sally Field,1.0,1.194795e+08,1.471527e+09,2,comedy
5,14.0,American Beauty,1999-09-15,122,en,8.000,12880,['UnitedStatesofAmerica'],English,1999,...,8211.0,Mena Suvari,1.0,516.0,Annette Bening,1.0,2.898646e+07,6.885186e+08,3,romance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19096,1511417.0,Bāhubali: The Epic,2025-10-29,224,te,5.985,34,['India'],"?????, हिन्दी, , தமிழ், తెలుగు",2025,...,215910.0,Rana Daggubati,2.0,141701.0,Ramya Krishnan,1.0,6.500000e+07,3.500000e+06,4,action
19099,1518784.0,Witnessed,2023-05-06,88,en,10.000,2,[],English,2023,...,3616795.0,Marcus Hopkins-Turner,2.0,2283871.0,Lau'rie Roach,0.0,1.056583e+04,5.599891e+04,2,action
19106,1537715.0,Banduan,2025-11-06,127,other,6.500,2,['Malaysia'],Bahasa melayu,2025,...,3836236.0,Abi Madyan,0.0,557749.0,Aaron Aziz,2.0,1.600000e+06,1.472934e+06,4,action
19115,1559535.0,Time Hoppers: The Silk Road,2025-10-29,80,en,4.000,1,['Canada'],"العربية, English, Türkçe",2025,...,5805027.0,Tareek Talati,0.0,5776371.0,Angel Haven Rey,0.0,3.000000e+06,6.923300e+04,4,animation
19117,1600196.0,Kausthubham,2010-03-19,113,en,0.000,0,[],NaN,2010,...,389667.0,Sukumari,1.0,584765.0,Vijayaraghavan,2.0,3.395774e+05,2.952847e+05,1,musical

In [148]:
data.isna().sum()

tmdbId                 0
title                  0
release_date           0
runtime                0
original_language      0
vote_average           0
vote_count             0
origin_countries       0
spoken_languages     131
year                   0
keywords             949
genres                13
director_id            9
director_name          9
director_gender        9
writer_id            202
writer_name          202
writer_gender        202
actor4_id            100
actor4_name          100
actor4_gender        100
actor2_id             20
actor2_name           20
actor2_gender         20
actor1_id              9
actor1_name            9
actor1_gender          9
actor5_id            376
actor5_name          376
actor5_gender        376
actor3_id             46
actor3_name           46
actor3_gender         46
budget_adjusted        0
revenue_adjusted       0
quarter                0
main_genre            13
dtype: int64

In [149]:
data = data.dropna()

In [150]:
data.shape

(9194, 37)

Po usunięciu wszystkich brakujących danych pozostało ponad 9tys danych. Większość braków była w starych filmach przed rokiem 1980, tak samo większość braków w budżecie pochodziła z tamtego okresu oraz większość filmów krótszych niż 1 godzina.

## Język oryginalny

In [151]:
# Zostawiamy 20 najczęstszych języków + kategoria other na wszystkie inne
data["original_language"].value_counts()

original_language
en       7236
fr        328
hi        260
other     249
es        163
ja        124
ru        116
ko         97
zh         92
it         82
ar         75
ta         71
de         59
cn         57
te         43
no         38
pt         29
sv         24
ml         19
tr         18
pl         14
Name: count, dtype: int64

## Kraj pochodzenia

In [152]:
# Zostawiamy 20 najczęstszych krajów + kategoria other na wszystkie inne
# Bierzemy pod uwagę tylko pierwszy kraj, jeśli pojawa się więcej na liście

data['origin_countries'] = data['origin_countries'].str.replace(r"[\[\]']", "", regex=True).str.strip()

wszystkie_kraje = data['origin_countries'].str.split(', ').explode()
top_20_kraje = wszystkie_kraje.value_counts().head(20).index.tolist()

def kategoryzuj_kraj(row):
    kraje = row.split(', ')
    glowny_kraj = kraje[0] # Bierzemy pierwszy wymieniony kraj jako dominujący
    
    if glowny_kraj == 'UnitedStatesofAmerica':
        return 'USA'
    elif glowny_kraj in top_20_kraje:
        return glowny_kraj
    else:
        return 'Other'

data['main_country'] = data['origin_countries'].apply(kategoryzuj_kraj)


print(data['main_country'].value_counts())

main_country
USA              5048
UnitedKingdom     660
Other             642
France            501
India             430
Canada            348
Germany           273
Australia         170
China             156
Japan             152
Belgium           121
Spain             118
Russia            112
Italy             112
SouthKorea         99
HongKong           75
Denmark            52
Ireland            47
Mexico             37
Sweden             22
Netherlands        19
Name: count, dtype: int64

## Keywords

In [153]:
all_keywords = data['keywords'].str.split(',').explode().str.strip()

all_keywords = all_keywords[all_keywords != ""]

top_100_keywords = all_keywords.value_counts().head(100)

print(top_100_keywords.to_string())

keywords
original                  861
action                    574
comedy                    493
horror                    339
drama                     328
family                    317
sequel                    316
based on true story       308
based on a book           298
based on novel or book    293
murder                    241
remake                    239
woman director            236
animation                 224
mentor                    223
romantic                  213
predictable               196
supernatural              193
independent film          191
violence                  189
sports                    189
weird                     183
friendship                181
coming of age             179
chick flick               177
adapted from:book         176
chase                     175
relationships             173
visually appealing        172
good action               172
love                      169
suspense                  169
girlie movie              167
teen movie                167
romantic comedy           164
new york city             162
serial killer             160
revenge                   159
funny                     157
musical                   152
high school               148
love story                147
martial arts              143
fight scenes              142
small town                140
superhero                 135
alien                     133
romance                   129
biography                 128
true story                126
fantasy world             126
feel-good                 120
franchise                 120
sci-fi                    119
based on a true story     119
teen                      119
hilarious                 119
duringcreditsstinger      118
adventure                 116
crime                     116
gunfight                  112
slasher                   110
brutality                 109
police                    108
gangster                  108
suspenseful               108
world war ii              107
france                    106
melancholic               105
california                105
corruption                102
drugs                     100
computer animation         98
biopic                     98
parody                     97
biographical               95
obsession                  94
loneliness                 94
creepy                     93
los angeles                93
based on book              93
silly fun                  92
splatter                   92
women                      91
pornography                91
scifi                      91
animals                    91
death                      89
kids and family            89
superheroes                88
absurd                     87
storytelling               87
tense                      86
politics                   86
christmas                  85
cartoon                    84
investigation              84
future                     84
super hero                 83
aftercreditsstinger        83

In [154]:
print(data["main_genre"].value_counts())

main_genre
comedy         2182
action         1447
horror          759
romance         695
thriller        585
crime           542
drama           542
adventure       517
animation       332
family          278
history         272
sci-fi          265
fantasy         259
mystery         158
musical         136
war             130
western          51
documentary      44
Name: count, dtype: int64

In [ ]:
wybrane_keywords = ['sequel', 'prequel', 'based', 'murder', 'remake', 'love', 'supernatural', 'violence',
                    'sport', 'friendship', 'weird', 'teen',  'funny', 'alien', 'superhero', 'magic',
                    'chase', 'heist', 'book', 'revenge', 'town', 'city', 'village', 'biography',
                    'police', 'gangster', 'war', 'christmas', 'politics', 'holiday', 'death', 
                    'suspense', 'melancholic', 'drugs', 'alcohol', 'future', 'detective', 'time travel',
                    'true stroy', 'spy', 'dark']

len(wybrane_keywords)

41

In [156]:
wzorzec = '|'.join(wybrane_keywords)

# Sprawdzamy ile filmów mieliśmy na początku
print(f"Filmy przed filtrowaniem: {len(data)}")

data[data['keywords'].str.contains(wzorzec, case=False, na=False, regex=True)].copy()

Filmy przed filtrowaniem: 9194

,tmdbId,title,release_date,runtime,original_language,vote_average,vote_count,origin_countries,spoken_languages,year,...,actor5_name,actor5_gender,actor3_id,actor3_name,actor3_gender,budget_adjusted,revenue_adjusted,quarter,main_genre,main_country
1,6.0,Judgment Night,1993-10-15,109,en,6.469,368,UnitedStatesofAmerica,English,1993,...,Cuba Gooding Jr.,2.0,12799.0,Jeremy Piven,2.0,4.678756e+07,2.704085e+07,4,action,USA
6,16.0,Dancer in the Dark,2000-09-01,140,en,7.850,1961,"Denmark, Finland, France, Germany, Iceland, Ne...",English,2000,...,Catherine Deneuve,1.0,52.0,David Morse,2.0,2.336985e+07,7.489784e+07,3,crime,Denmark
9,20.0,My Life Without Me,2003-03-07,106,en,6.079,496,"Canada, Spain",English,2003,...,Amanda Plummer,1.0,100.0,Scott Speedman,2.0,4.374226e+06,2.152119e+07,1,romance,Canada
11,24.0,Kill Bill: Vol. 1,2003-10-10,111,en,8.000,18683,UnitedStatesofAmerica,"English, 日本語, Français",2003,...,Vivica A. Fox,1.0,140.0,Lucy Liu,1.0,5.249071e+07,3.165296e+08,4,action,USA
12,25.0,Jarhead,2005-11-04,123,en,6.680,3128,"UnitedKingdom, UnitedStatesofAmerica","English, Español, العربية, Latin",2005,...,Peter Sarsgaard,2.0,134.0,Jamie Foxx,2.0,1.186887e+08,1.600255e+08,4,war,UnitedKingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19096,1511417.0,Bāhubali: The Epic,2025-10-29,224,te,5.985,34,India,"?????, हिन्दी, , தமிழ், తెలుగు",2025,...,Rana Daggubati,2.0,141701.0,Ramya Krishnan,1.0,6.500000e+07,3.500000e+06,4,action,India
19099,1518784.0,Witnessed,2023-05-06,88,en,10.000,2,,English,2023,...,Marcus Hopkins-Turner,2.0,2283871.0,Lau'rie Roach,0.0,1.056583e+04,5.599891e+04,2,action,Other
19106,1537715.0,Banduan,2025-11-06,127,other,6.500,2,Malaysia,Bahasa melayu,2025,...,Abi Madyan,0.0,557749.0,Aaron Aziz,2.0,1.600000e+06,1.472934e+06,4,action,Other
19111,1549541.0,Queen Mary - A Legend of the Atlantic,1993-06-12,51,en,4.000,1,"UnitedKingdom, UnitedStatesofAmerica",English,1993,...,David Ellery,0.0,5701177.0,John Smith,0.0,2.005181e+05,2.227979e+05,2,documentary,UnitedKingdom
19115,1559535.0,Time Hoppers: The Silk Road,2025-10-29,80,en,4.000,1,Canada,"العربية, English, Türkçe",2025,...,Tareek Talati,0.0,5776371.0,Angel Haven Rey,0.0,3.000000e+06,6.923300e+04,4,animation,Canada

## Zapis do ramki już bez braków danych, odpowiednio przefiltrowanych itp

In [157]:
data.to_csv("../data/merged/NEW_clean_data.csv", index = False)

## KODOWANIE 0-1

Do ramki **data_coded** przekazujemy już zakodowane kolumny 0-1 które będą szły do modelu

In [158]:
data_coded = data.copy()

- gatunek
- język

- kraj pochodzenia
- słowa kluczowe

In [159]:
genres_encoded = data['genres'].str.get_dummies(sep=', ')
data_coded = pd.concat([data_coded, genres_encoded], axis=1)

In [160]:
language_encoded = pd.get_dummies(data_coded['original_language'], prefix='lang', dtype=int)
data_coded = pd.concat([data_coded, language_encoded], axis=1)

In [161]:
country_encoded = pd.get_dummies(data_coded['main_country'], dtype=int)
data_coded = pd.concat([data_coded, country_encoded], axis=1)

In [162]:
for keyword in wybrane_keywords:

    col_name = f"kw_{keyword.replace(' ', '_')}"
    data_coded[col_name] = data_coded['keywords'].str.contains(keyword, case=False, na=False).astype(int)

In [163]:
data_coded.to_csv("../data/merged/data_coded.csv", index = False)